language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest --pyargs app --pylama --cov=app tests/
after_success:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
- coveralls
after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
deploy:
  provider: gae
  keyfile: client-secret.json
  project: ppa-2-team-1
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_081c528cdb76_key -iv $encrypted_081c528cdb76_iv
  -in client-secret.json.enc -out client-secret.json -d
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=5000 http://localhost &
sudo: required
addons:
  chrome: stable
