language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - git clone https://github.com/drbyron-github-classroom/ppa-2-sw-testing-qa-spring-2018-team-1
script:
  - pytest --pyargs app --pylama
after_success:
  - coveralls